roles:
  all: ["Admin", "Customer"]
  admin: "Admin"
  customer: "Customer"
inventory:
  buffer_unit: 5
  status:
    free: "available"
    lock: "lock"
shipment:
  status:
    packing: "包裝"
    delivered: "寄出"
    received: "已收貨"
  method:
    post: "郵局便利袋"
    fami_port: "全家超商取貨"
order:
  status:
    shopping: "購物中"
    payment_pending: "待付款"
    packing: "包裝中"
    delivered: "已寄出"
    received: "已送達"
promotion:
  scope:
    all: ["Order", "LineItem"]
    order: "Order"
    line_item: "LineItem"
payment:
  method:
    credit_card: "Credit Card"
    atm: "ATM"
    cash: "Cash"
