roles:
  all: ["Admin", "Customer"]
  admin: "Admin"
  customer: "Customer"
inventory:
  buffer_unit: 5
  status:
    free: "available"
    lock: "lock"
shipment:
  status:
    packing: "packing"
    delivered: "delivered"
    received: "received"
  method:
    post: "post"
    fami_port: "fami_port"
order:
  status:
    shopping: "shopping"
    payment_pending: "payment_pending"
    packing: "packing"
    delivered: "delivered"
    received: "received"
promotion:
  scope:
    all: ["Order", "LineItem"]
    order: "Order"
    product: "Product"
    line_item: "LineItem"
payment:
  method:
    credit_card: "Credit Card"
    atm: "ATM"
    cash: "Cash"
